[tool.poetry]
name = "pythonix"
version = "1.0.8"
description = "Rust and Gleam like functional programming in Python, complete with Results, pipes, and currying"
authors = ["jhok2013 <jhok2013@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.31.0"
typing-extensions = "^4.11.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
